### ISSUE TITLE
Are tags wrong?

### ISSUE THREAD

**Issue by nico202** [JuliaBinaryWrappers/FriBidi_jll.jl#2]
Hi, it seems that there's an off-by-one error in the tags.  Example:

FriBidi-v1.0.5+5
@jlbuild jlbuild released this on Aug 26, 2020 · 1 commit to master since this release
FriBidi_jll build 1.0.5+4

Is it 1.0.5+4 or 1.0.5+5?
Thanks

**Comment by giordano** [comment]
Yes, most old tags of these packages are misaligned, it's a known situation but also not relevant for the package manager which ignores git tags
